import turtle

turtle.shape('turtle')


def numeral(n):
    if n == 0:
        turtle.left(90)
        turtle.forward(180)
        turtle.left(90)
        turtle.forward(90)
        turtle.left(90)
        turtle.forward(180)
        turtle.left(90)
        turtle.forward(90)
    elif n == 1:
        turtle.left(90)
        turtle.forward(180)
        turtle.left(135)
        turtle.forward(126)
        turtle.left(135)
    elif n == 2:
        turtle.left(180)
        turtle.forward(90)
        turtle.right(135)
        turtle.forward(126)
        turtle.left(45)
        turtle.forward(90)
        turtle.left(90)
        turtle.forward(90)
        turtle.left(180)
    elif n == 3:
        turtle.penup()
        turtle.left(180)
        turtle.forward(90)
        turtle.pendown()
        turtle.right(135)
        turtle.forward(126)
        turtle.left(135)
        turtle.forward(90)
        turtle.right(135)
        turtle.forward(126)
        turtle.left(135)
        turtle.forward(90)
        turtle.left(180)
    elif n == 4:
        turtle.left(90)
        turtle.forward(180)
        turtle.left(90)
        turtle.penup()
        turtle.forward(90)
        turtle.pendown()
        turtle.left(90)
        turtle.forward(90)
        turtle.left(90)
        turtle.forward(90)
    elif n == 5:
        turtle.left(180)
        turtle.forward(90)
        turtle.backward(90)
        turtle.right(90)
        turtle.forward(90)
        turtle.left(90)
        turtle.forward(90)
        turtle.right(90)
        turtle.forward(90)
        turtle.right(90)
        turtle.forward(90)
    elif n == 6:
        turtle.left(180)
        turtle.forward(90)
        turtle.backward(90)
        turtle.right(90)
        turtle.forward(90)
        turtle.left(90)
        turtle.forward(90)
        turtle.left(90)
        turtle.forward(90)
        turtle.backward(90)
        turtle.left(135)
        turtle.forward(126)
        turtle.right(45)
    elif n == 7:
        turtle.penup()
        turtle.left(180)
        turtle.forward(90)
        turtle.pendown()
        turtle.right(90)
        turtle.forward(90)
        turtle.right(45)
        turtle.forward(126)
        turtle.left(135)
        turtle.forward(90)
        turtle.left(180)
    elif n == 8:
        turtle.left(90)
        turtle.forward(90)
        turtle.left(90)
        turtle.forward(90)
        turtle.backward(90)
        turtle.right(90)
        turtle.forward(90)
        turtle.left(90)
        turtle.forward(90)
        turtle.left(90)
        turtle.forward(180)
        turtle.left(90)
        turtle.forward(90)
    else:
        turtle.backward(90)
        turtle.forward(90)
        turtle.left(90)
        turtle.forward(90)
        turtle.left(90)
        turtle.forward(90)
        turtle.backward(90)
        turtle.right(90)
        turtle.forward(90)
        turtle.left(90)
        turtle.forward(90)
        turtle.left(90)
        turtle.forward(90)
        turtle.left(90)


s = str(input())      
for i in range(len(s)):
    turtle.penup()
    turtle.goto(i * 100, 0)
    turtle.pendown()
    numeral(int(s[i]))
